# Generated by Django 4.2.11 on 2026-06-24 14:12

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.ForeignKey(default=order.models.Job.default_status, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='order.jobstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
