# Generated by Django 4.2.11 on 2026-06-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_job_job_id_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_change_assignee', 'Can change assignee on a job')]},
        ),
    ]
