# Generated by Django 4.2.11 on 2026-06-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_change_status', 'Can change status on a job')]},
        ),
    ]
