# Generated by Django 4.2.30 on 2026-06-25 17:14

from django.db import migrations, models
import django.db.models.deletion


def migrate_customers_forward(apps, schema_editor):
    """Create Customer records from existing order data and set the FK."""
    Order = apps.get_model('order', 'Order')
    Customer = apps.get_model('order', 'Customer')
    for order in Order.objects.all():
        customer, _ = Customer.objects.get_or_create(
            mobile_number=order.mobile_number,
            defaults={'name': order.customer_name},
        )
        order.customer = customer
        order.save(update_fields=['customer'])


def migrate_customers_backward(apps, schema_editor):
    """Restore customer_name / mobile_number from the Customer FK."""
    Order = apps.get_model('order', 'Order')
    for order in Order.objects.select_related('customer').all():
        if order.customer:
            order.customer_name = order.customer.name
            order.mobile_number = order.customer.mobile_number
            order.save(update_fields=['customer_name', 'mobile_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_job_delivery_date_order_order_date'),
    ]

    operations = [
        # 1. Create the Customer table
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # 2. Add nullable customer FK (old fields still exist at this point)
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.customer'),
        ),
        # 3. Populate the FK from existing customer_name / mobile_number
        migrations.RunPython(migrate_customers_forward, migrate_customers_backward),
        # 4. Drop the old fields
        migrations.RemoveField(model_name='order', name='customer_name'),
        migrations.RemoveField(model_name='order', name='mobile_number'),
    ]
