# Generated by Django 4.2.30 on 2026-06-25 17:45

from django.db import migrations, models


def init_sequences(apps, schema_editor):
    """Seed the Sequence counters with the max IDs already in the DB."""
    Order = apps.get_model('order', 'Order')
    Job = apps.get_model('order', 'Job')
    Sequence = apps.get_model('order', 'Sequence')

    orders = Order.objects.all()
    if orders.exists():
        max_order = max(int(o.order_id.split('-')[1]) for o in orders)
        Sequence.objects.create(name='order', value=max_order)
    else:
        Sequence.objects.create(name='order', value=0)

    jobs = Job.objects.all()
    if jobs.exists():
        max_job = max(int(j.job_id.split('-')[1]) for j in jobs)
        Sequence.objects.create(name='job', value=max_job)
    else:
        Sequence.objects.create(name='job', value=0)


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_add_customer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(init_sequences, migrations.RunPython.noop),
    ]
